// flow-typed signature: a71345234a287981ce8dd8fc47461d58
// flow-typed version: <<STUB>>/boom-js-client_v1.3.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boom-js-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boom-js-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boom-js-client/dist/base64' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/Client' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/Client.test' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/Handler' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/index' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/index.test' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/jsonTransform' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/request' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/request.test' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/toAst' {
  declare module.exports: any;
}

declare module 'boom-js-client/dist/toTs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boom-js-client/dist/base64.js' {
  declare module.exports: $Exports<'boom-js-client/dist/base64'>;
}
declare module 'boom-js-client/dist/Client.js' {
  declare module.exports: $Exports<'boom-js-client/dist/Client'>;
}
declare module 'boom-js-client/dist/Client.test.js' {
  declare module.exports: $Exports<'boom-js-client/dist/Client.test'>;
}
declare module 'boom-js-client/dist/Handler.js' {
  declare module.exports: $Exports<'boom-js-client/dist/Handler'>;
}
declare module 'boom-js-client/dist/index.js' {
  declare module.exports: $Exports<'boom-js-client/dist/index'>;
}
declare module 'boom-js-client/dist/index.test.js' {
  declare module.exports: $Exports<'boom-js-client/dist/index.test'>;
}
declare module 'boom-js-client/dist/jsonTransform.js' {
  declare module.exports: $Exports<'boom-js-client/dist/jsonTransform'>;
}
declare module 'boom-js-client/dist/request.js' {
  declare module.exports: $Exports<'boom-js-client/dist/request'>;
}
declare module 'boom-js-client/dist/request.test.js' {
  declare module.exports: $Exports<'boom-js-client/dist/request.test'>;
}
declare module 'boom-js-client/dist/toAst.js' {
  declare module.exports: $Exports<'boom-js-client/dist/toAst'>;
}
declare module 'boom-js-client/dist/toTs.js' {
  declare module.exports: $Exports<'boom-js-client/dist/toTs'>;
}
