parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true
    ecmaVersion: 2018
    sourceType: module

env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:flowtype/recommended

settings:
  react:
    version: 16.4.2

rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  semi:
    - error
    - never
  no-console:
    - off
  react/prop-types:
    - off
  quotes:
    - error
    - double
  react/no-find-dom-node:
    - off
  no-debugger:
    - off
