checksumBehavior: ignore

compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0076
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-github.cjs
    spec: "@yarnpkg/plugin-github"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
