// flow-typed signature: e2e75d48b1209cca05f7ed3312d9efd7
// flow-typed version: <<STUB>>/babel-plugin-source-map-support_v^2.1.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-source-map-support'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-source-map-support' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-source-map-support/dist/index.esm' {
  declare module.exports: any;
}

declare module 'babel-plugin-source-map-support/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-source-map-support/dist/index.esm.js' {
  declare module.exports: $Exports<'babel-plugin-source-map-support/dist/index.esm'>;
}
declare module 'babel-plugin-source-map-support/dist/index' {
  declare module.exports: $Exports<'babel-plugin-source-map-support/dist'>;
}
declare module 'babel-plugin-source-map-support/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-source-map-support/dist'>;
}
