// flow-typed signature: 33d7e372cd1e503ad09933e2d67d79bb
// flow-typed version: <<STUB>>/babel-plugin-source-map-support_v^2.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-source-map-support'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-source-map-support' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-source-map-support/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-source-map-support/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-source-map-support/dist/index'>;
}
