// flow-typed signature: 538f39e5f2189ed914639ba7e0819dc7
// flow-typed version: <<STUB>>/chrono-node_v^1.3.11/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrono-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrono-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrono-node/chrono' {
  declare module.exports: any;
}

declare module 'chrono-node/chrono.min' {
  declare module.exports: any;
}

declare module 'chrono-node/karma.conf' {
  declare module.exports: any;
}

declare module 'chrono-node/src/chrono' {
  declare module.exports: any;
}

declare module 'chrono-node/src/options' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/de/DECasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/de/DEDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/de/DEMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/de/DEMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/de/DESlashDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/de/DETimeAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/de/DETimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/de/DEWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENISOFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENMonthNameMiddleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENRelativeDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENSlashDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENSlashDateFormatStartWithYearParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENSlashMonthFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENTimeAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENTimeLaterFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/en/ENWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/es/ESCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/es/ESDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/es/ESMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/es/ESSlashDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/es/ESTimeAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/es/ESTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/es/ESWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/fr/FRCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/fr/FRDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/fr/FRMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/fr/FRRelativeDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/fr/FRSlashDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/fr/FRTimeAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/fr/FRTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/fr/FRWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ja/JPCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/ja/JPStandardParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/parser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/zh-Hant/ZHHantCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/zh-Hant/ZHHantDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/zh-Hant/ZHHantDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/zh-Hant/ZHHantTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/parsers/zh-Hant/ZHHantWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/ConcordanceTimezoneRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/de/DEMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/de/DEMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/en/ENMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/en/ENMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/en/ENMergeWeekdayRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/en/ENPrioritizeSpecificDateRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/ExtractTimezoneAbbrRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/ExtractTimezoneOffsetRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/ForwardDateRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/fr/FRMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/fr/FRMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/ja/JPMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/OverlapRemovalRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/refiner' {
  declare module.exports: any;
}

declare module 'chrono-node/src/refiners/UnlikelyFormatFilter' {
  declare module.exports: any;
}

declare module 'chrono-node/src/result' {
  declare module.exports: any;
}

declare module 'chrono-node/src/timezone' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/DE' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/EN' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/ES' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/FR' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/JP' {
  declare module.exports: any;
}

declare module 'chrono-node/src/utils/ZH-Hant' {
  declare module.exports: any;
}

declare module 'chrono-node/test/de/de_casual.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/de/de_dash.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/de/de_deadline.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/de/de_little_endian.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/de/de_time_ago.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/de/de_time_exp.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/de/de_weekday.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/de/de.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_casual.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_dash.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_deadline.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_example.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_inter_std.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_little_endian.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_middle_endian.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_month.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_option_forward.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_relative.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_slash.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_time_ago.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_time_exp.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_time_from_now.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_time_later.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en_weekday.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/en/en.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/es/es_casual.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/es/es_dash.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/es/es_deadline.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/es/es_little_endian.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/es/es_slash.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/es/es_time_ago.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/es/es_time_exp.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_casual.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_dash.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_deadline.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_little_endian.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_relative.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_slash.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_time_ago.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_time_exp.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/fr/fr_weekday.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/ja/ja_casual.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/ja/ja_standard.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/system.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/zh/zh_hant_casual.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/zh/zh_hant_date.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/zh/zh_hant_deadline.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/zh/zh_hant_time_exp.test' {
  declare module.exports: any;
}

declare module 'chrono-node/test/zh/zh_hant_weekday.test' {
  declare module.exports: any;
}

declare module 'chrono-node/timezone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrono-node/chrono.js' {
  declare module.exports: $Exports<'chrono-node/chrono'>;
}
declare module 'chrono-node/chrono.min.js' {
  declare module.exports: $Exports<'chrono-node/chrono.min'>;
}
declare module 'chrono-node/karma.conf.js' {
  declare module.exports: $Exports<'chrono-node/karma.conf'>;
}
declare module 'chrono-node/src/chrono.js' {
  declare module.exports: $Exports<'chrono-node/src/chrono'>;
}
declare module 'chrono-node/src/options.js' {
  declare module.exports: $Exports<'chrono-node/src/options'>;
}
declare module 'chrono-node/src/parsers/de/DECasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/de/DECasualDateParser'>;
}
declare module 'chrono-node/src/parsers/de/DEDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/de/DEDeadlineFormatParser'>;
}
declare module 'chrono-node/src/parsers/de/DEMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/de/DEMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/src/parsers/de/DEMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/de/DEMonthNameParser'>;
}
declare module 'chrono-node/src/parsers/de/DESlashDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/de/DESlashDateFormatParser'>;
}
declare module 'chrono-node/src/parsers/de/DETimeAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/de/DETimeAgoFormatParser'>;
}
declare module 'chrono-node/src/parsers/de/DETimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/de/DETimeExpressionParser'>;
}
declare module 'chrono-node/src/parsers/de/DEWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/de/DEWeekdayParser'>;
}
declare module 'chrono-node/src/parsers/en/ENCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENCasualDateParser'>;
}
declare module 'chrono-node/src/parsers/en/ENCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENCasualTimeParser'>;
}
declare module 'chrono-node/src/parsers/en/ENDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENDeadlineFormatParser'>;
}
declare module 'chrono-node/src/parsers/en/ENISOFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENISOFormatParser'>;
}
declare module 'chrono-node/src/parsers/en/ENMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/src/parsers/en/ENMonthNameMiddleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENMonthNameMiddleEndianParser'>;
}
declare module 'chrono-node/src/parsers/en/ENMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENMonthNameParser'>;
}
declare module 'chrono-node/src/parsers/en/ENRelativeDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENRelativeDateFormatParser'>;
}
declare module 'chrono-node/src/parsers/en/ENSlashDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENSlashDateFormatParser'>;
}
declare module 'chrono-node/src/parsers/en/ENSlashDateFormatStartWithYearParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENSlashDateFormatStartWithYearParser'>;
}
declare module 'chrono-node/src/parsers/en/ENSlashMonthFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENSlashMonthFormatParser'>;
}
declare module 'chrono-node/src/parsers/en/ENTimeAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENTimeAgoFormatParser'>;
}
declare module 'chrono-node/src/parsers/en/ENTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENTimeExpressionParser'>;
}
declare module 'chrono-node/src/parsers/en/ENTimeLaterFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENTimeLaterFormatParser'>;
}
declare module 'chrono-node/src/parsers/en/ENWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/en/ENWeekdayParser'>;
}
declare module 'chrono-node/src/parsers/es/ESCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/es/ESCasualDateParser'>;
}
declare module 'chrono-node/src/parsers/es/ESDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/es/ESDeadlineFormatParser'>;
}
declare module 'chrono-node/src/parsers/es/ESMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/es/ESMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/src/parsers/es/ESSlashDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/es/ESSlashDateFormatParser'>;
}
declare module 'chrono-node/src/parsers/es/ESTimeAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/es/ESTimeAgoFormatParser'>;
}
declare module 'chrono-node/src/parsers/es/ESTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/es/ESTimeExpressionParser'>;
}
declare module 'chrono-node/src/parsers/es/ESWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/es/ESWeekdayParser'>;
}
declare module 'chrono-node/src/parsers/fr/FRCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/fr/FRCasualDateParser'>;
}
declare module 'chrono-node/src/parsers/fr/FRDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/fr/FRDeadlineFormatParser'>;
}
declare module 'chrono-node/src/parsers/fr/FRMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/fr/FRMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/src/parsers/fr/FRRelativeDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/fr/FRRelativeDateFormatParser'>;
}
declare module 'chrono-node/src/parsers/fr/FRSlashDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/fr/FRSlashDateFormatParser'>;
}
declare module 'chrono-node/src/parsers/fr/FRTimeAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/fr/FRTimeAgoFormatParser'>;
}
declare module 'chrono-node/src/parsers/fr/FRTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/fr/FRTimeExpressionParser'>;
}
declare module 'chrono-node/src/parsers/fr/FRWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/fr/FRWeekdayParser'>;
}
declare module 'chrono-node/src/parsers/ja/JPCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ja/JPCasualDateParser'>;
}
declare module 'chrono-node/src/parsers/ja/JPStandardParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/ja/JPStandardParser'>;
}
declare module 'chrono-node/src/parsers/parser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/parser'>;
}
declare module 'chrono-node/src/parsers/zh-Hant/ZHHantCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/zh-Hant/ZHHantCasualDateParser'>;
}
declare module 'chrono-node/src/parsers/zh-Hant/ZHHantDateParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/zh-Hant/ZHHantDateParser'>;
}
declare module 'chrono-node/src/parsers/zh-Hant/ZHHantDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/zh-Hant/ZHHantDeadlineFormatParser'>;
}
declare module 'chrono-node/src/parsers/zh-Hant/ZHHantTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/zh-Hant/ZHHantTimeExpressionParser'>;
}
declare module 'chrono-node/src/parsers/zh-Hant/ZHHantWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/src/parsers/zh-Hant/ZHHantWeekdayParser'>;
}
declare module 'chrono-node/src/refiners/ConcordanceTimezoneRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/ConcordanceTimezoneRefiner'>;
}
declare module 'chrono-node/src/refiners/de/DEMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/de/DEMergeDateRangeRefiner'>;
}
declare module 'chrono-node/src/refiners/de/DEMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/de/DEMergeDateTimeRefiner'>;
}
declare module 'chrono-node/src/refiners/en/ENMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/en/ENMergeDateRangeRefiner'>;
}
declare module 'chrono-node/src/refiners/en/ENMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/en/ENMergeDateTimeRefiner'>;
}
declare module 'chrono-node/src/refiners/en/ENMergeWeekdayRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/en/ENMergeWeekdayRefiner'>;
}
declare module 'chrono-node/src/refiners/en/ENPrioritizeSpecificDateRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/en/ENPrioritizeSpecificDateRefiner'>;
}
declare module 'chrono-node/src/refiners/ExtractTimezoneAbbrRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/ExtractTimezoneAbbrRefiner'>;
}
declare module 'chrono-node/src/refiners/ExtractTimezoneOffsetRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/ExtractTimezoneOffsetRefiner'>;
}
declare module 'chrono-node/src/refiners/ForwardDateRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/ForwardDateRefiner'>;
}
declare module 'chrono-node/src/refiners/fr/FRMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/fr/FRMergeDateRangeRefiner'>;
}
declare module 'chrono-node/src/refiners/fr/FRMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/fr/FRMergeDateTimeRefiner'>;
}
declare module 'chrono-node/src/refiners/ja/JPMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/ja/JPMergeDateRangeRefiner'>;
}
declare module 'chrono-node/src/refiners/OverlapRemovalRefiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/OverlapRemovalRefiner'>;
}
declare module 'chrono-node/src/refiners/refiner.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/refiner'>;
}
declare module 'chrono-node/src/refiners/UnlikelyFormatFilter.js' {
  declare module.exports: $Exports<'chrono-node/src/refiners/UnlikelyFormatFilter'>;
}
declare module 'chrono-node/src/result.js' {
  declare module.exports: $Exports<'chrono-node/src/result'>;
}
declare module 'chrono-node/src/timezone.js' {
  declare module.exports: $Exports<'chrono-node/src/timezone'>;
}
declare module 'chrono-node/src/utils/DE.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/DE'>;
}
declare module 'chrono-node/src/utils/EN.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/EN'>;
}
declare module 'chrono-node/src/utils/ES.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/ES'>;
}
declare module 'chrono-node/src/utils/FR.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/FR'>;
}
declare module 'chrono-node/src/utils/JP.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/JP'>;
}
declare module 'chrono-node/src/utils/ZH-Hant.js' {
  declare module.exports: $Exports<'chrono-node/src/utils/ZH-Hant'>;
}
declare module 'chrono-node/test/de/de_casual.test.js' {
  declare module.exports: $Exports<'chrono-node/test/de/de_casual.test'>;
}
declare module 'chrono-node/test/de/de_dash.test.js' {
  declare module.exports: $Exports<'chrono-node/test/de/de_dash.test'>;
}
declare module 'chrono-node/test/de/de_deadline.test.js' {
  declare module.exports: $Exports<'chrono-node/test/de/de_deadline.test'>;
}
declare module 'chrono-node/test/de/de_little_endian.test.js' {
  declare module.exports: $Exports<'chrono-node/test/de/de_little_endian.test'>;
}
declare module 'chrono-node/test/de/de_time_ago.test.js' {
  declare module.exports: $Exports<'chrono-node/test/de/de_time_ago.test'>;
}
declare module 'chrono-node/test/de/de_time_exp.test.js' {
  declare module.exports: $Exports<'chrono-node/test/de/de_time_exp.test'>;
}
declare module 'chrono-node/test/de/de_weekday.test.js' {
  declare module.exports: $Exports<'chrono-node/test/de/de_weekday.test'>;
}
declare module 'chrono-node/test/de/de.test.js' {
  declare module.exports: $Exports<'chrono-node/test/de/de.test'>;
}
declare module 'chrono-node/test/en/en_casual.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_casual.test'>;
}
declare module 'chrono-node/test/en/en_dash.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_dash.test'>;
}
declare module 'chrono-node/test/en/en_deadline.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_deadline.test'>;
}
declare module 'chrono-node/test/en/en_example.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_example.test'>;
}
declare module 'chrono-node/test/en/en_inter_std.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_inter_std.test'>;
}
declare module 'chrono-node/test/en/en_little_endian.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_little_endian.test'>;
}
declare module 'chrono-node/test/en/en_middle_endian.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_middle_endian.test'>;
}
declare module 'chrono-node/test/en/en_month.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_month.test'>;
}
declare module 'chrono-node/test/en/en_option_forward.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_option_forward.test'>;
}
declare module 'chrono-node/test/en/en_relative.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_relative.test'>;
}
declare module 'chrono-node/test/en/en_slash.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_slash.test'>;
}
declare module 'chrono-node/test/en/en_time_ago.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_time_ago.test'>;
}
declare module 'chrono-node/test/en/en_time_exp.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_time_exp.test'>;
}
declare module 'chrono-node/test/en/en_time_from_now.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_time_from_now.test'>;
}
declare module 'chrono-node/test/en/en_time_later.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_time_later.test'>;
}
declare module 'chrono-node/test/en/en_weekday.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en_weekday.test'>;
}
declare module 'chrono-node/test/en/en.test.js' {
  declare module.exports: $Exports<'chrono-node/test/en/en.test'>;
}
declare module 'chrono-node/test/es/es_casual.test.js' {
  declare module.exports: $Exports<'chrono-node/test/es/es_casual.test'>;
}
declare module 'chrono-node/test/es/es_dash.test.js' {
  declare module.exports: $Exports<'chrono-node/test/es/es_dash.test'>;
}
declare module 'chrono-node/test/es/es_deadline.test.js' {
  declare module.exports: $Exports<'chrono-node/test/es/es_deadline.test'>;
}
declare module 'chrono-node/test/es/es_little_endian.test.js' {
  declare module.exports: $Exports<'chrono-node/test/es/es_little_endian.test'>;
}
declare module 'chrono-node/test/es/es_slash.test.js' {
  declare module.exports: $Exports<'chrono-node/test/es/es_slash.test'>;
}
declare module 'chrono-node/test/es/es_time_ago.test.js' {
  declare module.exports: $Exports<'chrono-node/test/es/es_time_ago.test'>;
}
declare module 'chrono-node/test/es/es_time_exp.test.js' {
  declare module.exports: $Exports<'chrono-node/test/es/es_time_exp.test'>;
}
declare module 'chrono-node/test/fr/fr_casual.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_casual.test'>;
}
declare module 'chrono-node/test/fr/fr_dash.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_dash.test'>;
}
declare module 'chrono-node/test/fr/fr_deadline.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_deadline.test'>;
}
declare module 'chrono-node/test/fr/fr_little_endian.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_little_endian.test'>;
}
declare module 'chrono-node/test/fr/fr_relative.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_relative.test'>;
}
declare module 'chrono-node/test/fr/fr_slash.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_slash.test'>;
}
declare module 'chrono-node/test/fr/fr_time_ago.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_time_ago.test'>;
}
declare module 'chrono-node/test/fr/fr_time_exp.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_time_exp.test'>;
}
declare module 'chrono-node/test/fr/fr_weekday.test.js' {
  declare module.exports: $Exports<'chrono-node/test/fr/fr_weekday.test'>;
}
declare module 'chrono-node/test/ja/ja_casual.test.js' {
  declare module.exports: $Exports<'chrono-node/test/ja/ja_casual.test'>;
}
declare module 'chrono-node/test/ja/ja_standard.test.js' {
  declare module.exports: $Exports<'chrono-node/test/ja/ja_standard.test'>;
}
declare module 'chrono-node/test/system.test.js' {
  declare module.exports: $Exports<'chrono-node/test/system.test'>;
}
declare module 'chrono-node/test/zh/zh_hant_casual.test.js' {
  declare module.exports: $Exports<'chrono-node/test/zh/zh_hant_casual.test'>;
}
declare module 'chrono-node/test/zh/zh_hant_date.test.js' {
  declare module.exports: $Exports<'chrono-node/test/zh/zh_hant_date.test'>;
}
declare module 'chrono-node/test/zh/zh_hant_deadline.test.js' {
  declare module.exports: $Exports<'chrono-node/test/zh/zh_hant_deadline.test'>;
}
declare module 'chrono-node/test/zh/zh_hant_time_exp.test.js' {
  declare module.exports: $Exports<'chrono-node/test/zh/zh_hant_time_exp.test'>;
}
declare module 'chrono-node/test/zh/zh_hant_weekday.test.js' {
  declare module.exports: $Exports<'chrono-node/test/zh/zh_hant_weekday.test'>;
}
declare module 'chrono-node/timezone.js' {
  declare module.exports: $Exports<'chrono-node/timezone'>;
}
