// flow-typed signature: bd57d589cc8e2b3a826797880dea48c8
// flow-typed version: <<STUB>>/cross-unzip_v^0.2.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-unzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-unzip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cross-unzip/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cross-unzip/index' {
  declare module.exports: $Exports<'cross-unzip'>;
}
declare module 'cross-unzip/index.js' {
  declare module.exports: $Exports<'cross-unzip'>;
}
declare module 'cross-unzip/test/test.js' {
  declare module.exports: $Exports<'cross-unzip/test/test'>;
}
