// flow-typed signature: 00985d93e3acbb07ee143fde40cfc457
// flow-typed version: <<STUB>>/d3_v^5.5.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3/dist/d3' {
  declare module.exports: any;
}

declare module 'd3/dist/d3.min' {
  declare module.exports: any;
}

declare module 'd3/dist/d3.node' {
  declare module.exports: any;
}

declare module 'd3/dist/package' {
  declare module.exports: any;
}

declare module 'd3/rollup.config' {
  declare module.exports: any;
}

declare module 'd3/rollup.node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3/dist/d3.js' {
  declare module.exports: $Exports<'d3/dist/d3'>;
}
declare module 'd3/dist/d3.min.js' {
  declare module.exports: $Exports<'d3/dist/d3.min'>;
}
declare module 'd3/dist/d3.node.js' {
  declare module.exports: $Exports<'d3/dist/d3.node'>;
}
declare module 'd3/dist/package.js' {
  declare module.exports: $Exports<'d3/dist/package'>;
}
declare module 'd3/index' {
  declare module.exports: $Exports<'d3'>;
}
declare module 'd3/index.js' {
  declare module.exports: $Exports<'d3'>;
}
declare module 'd3/rollup.config.js' {
  declare module.exports: $Exports<'d3/rollup.config'>;
}
declare module 'd3/rollup.node.js' {
  declare module.exports: $Exports<'d3/rollup.node'>;
}
