// flow-typed signature: e8635c3cc4e7e35148d5fd7281c941b2
// flow-typed version: <<STUB>>/electron-winstaller_v^4.0.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-winstaller'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-winstaller' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-winstaller/lib' {
  declare module.exports: any;
}

declare module 'electron-winstaller/lib/options' {
  declare module.exports: any;
}

declare module 'electron-winstaller/lib/spawn-promise' {
  declare module.exports: any;
}

declare module 'electron-winstaller/lib/temp-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-winstaller/lib/index' {
  declare module.exports: $Exports<'electron-winstaller/lib'>;
}
declare module 'electron-winstaller/lib/index.js' {
  declare module.exports: $Exports<'electron-winstaller/lib'>;
}
declare module 'electron-winstaller/lib/options.js' {
  declare module.exports: $Exports<'electron-winstaller/lib/options'>;
}
declare module 'electron-winstaller/lib/spawn-promise.js' {
  declare module.exports: $Exports<'electron-winstaller/lib/spawn-promise'>;
}
declare module 'electron-winstaller/lib/temp-utils.js' {
  declare module.exports: $Exports<'electron-winstaller/lib/temp-utils'>;
}
