// flow-typed signature: 51f00243d6fd1d6de77ab4e3460f5711
// flow-typed version: <<STUB>>/electron-installer-dmg_v^3.0.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-installer-dmg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-installer-dmg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-installer-dmg/bin/electron-installer-dmg' {
  declare module.exports: any;
}

declare module 'electron-installer-dmg/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-installer-dmg/bin/electron-installer-dmg.js' {
  declare module.exports: $Exports<'electron-installer-dmg/bin/electron-installer-dmg'>;
}
declare module 'electron-installer-dmg/src/index' {
  declare module.exports: $Exports<'electron-installer-dmg/src'>;
}
declare module 'electron-installer-dmg/src/index.js' {
  declare module.exports: $Exports<'electron-installer-dmg/src'>;
}
