// flow-typed signature: 4578884a764d526b969ddc5c34da2f79
// flow-typed version: <<STUB>>/electron-dl_v^1.13.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-dl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-dl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-dl/index' {
  declare module.exports: $Exports<'electron-dl'>;
}
declare module 'electron-dl/index.js' {
  declare module.exports: $Exports<'electron-dl'>;
}
