// flow-typed signature: ccbba59c0b334c1ad1df58f717aca5bf
// flow-typed version: <<STUB>>/electron-log_v^4.1.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-log/src/catchErrors' {
  declare module.exports: any;
}

declare module 'electron-log/src/electronApi' {
  declare module.exports: any;
}

declare module 'electron-log/src' {
  declare module.exports: any;
}

declare module 'electron-log/src/log' {
  declare module.exports: any;
}

declare module 'electron-log/src/scope' {
  declare module.exports: any;
}

declare module 'electron-log/src/transform' {
  declare module.exports: any;
}

declare module 'electron-log/src/transform/object' {
  declare module.exports: any;
}

declare module 'electron-log/src/transform/style' {
  declare module.exports: any;
}

declare module 'electron-log/src/transform/template' {
  declare module.exports: any;
}

declare module 'electron-log/src/transports/console' {
  declare module.exports: any;
}

declare module 'electron-log/src/transports/file/file' {
  declare module.exports: any;
}

declare module 'electron-log/src/transports/file' {
  declare module.exports: any;
}

declare module 'electron-log/src/transports/file/packageJson' {
  declare module.exports: any;
}

declare module 'electron-log/src/transports/file/variables' {
  declare module.exports: any;
}

declare module 'electron-log/src/transports/ipc' {
  declare module.exports: any;
}

declare module 'electron-log/src/transports/remote' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-log/src/catchErrors.js' {
  declare module.exports: $Exports<'electron-log/src/catchErrors'>;
}
declare module 'electron-log/src/electronApi.js' {
  declare module.exports: $Exports<'electron-log/src/electronApi'>;
}
declare module 'electron-log/src/index' {
  declare module.exports: $Exports<'electron-log/src'>;
}
declare module 'electron-log/src/index.js' {
  declare module.exports: $Exports<'electron-log/src'>;
}
declare module 'electron-log/src/log.js' {
  declare module.exports: $Exports<'electron-log/src/log'>;
}
declare module 'electron-log/src/scope.js' {
  declare module.exports: $Exports<'electron-log/src/scope'>;
}
declare module 'electron-log/src/transform/index' {
  declare module.exports: $Exports<'electron-log/src/transform'>;
}
declare module 'electron-log/src/transform/index.js' {
  declare module.exports: $Exports<'electron-log/src/transform'>;
}
declare module 'electron-log/src/transform/object.js' {
  declare module.exports: $Exports<'electron-log/src/transform/object'>;
}
declare module 'electron-log/src/transform/style.js' {
  declare module.exports: $Exports<'electron-log/src/transform/style'>;
}
declare module 'electron-log/src/transform/template.js' {
  declare module.exports: $Exports<'electron-log/src/transform/template'>;
}
declare module 'electron-log/src/transports/console.js' {
  declare module.exports: $Exports<'electron-log/src/transports/console'>;
}
declare module 'electron-log/src/transports/file/file.js' {
  declare module.exports: $Exports<'electron-log/src/transports/file/file'>;
}
declare module 'electron-log/src/transports/file/index' {
  declare module.exports: $Exports<'electron-log/src/transports/file'>;
}
declare module 'electron-log/src/transports/file/index.js' {
  declare module.exports: $Exports<'electron-log/src/transports/file'>;
}
declare module 'electron-log/src/transports/file/packageJson.js' {
  declare module.exports: $Exports<'electron-log/src/transports/file/packageJson'>;
}
declare module 'electron-log/src/transports/file/variables.js' {
  declare module.exports: $Exports<'electron-log/src/transports/file/variables'>;
}
declare module 'electron-log/src/transports/ipc.js' {
  declare module.exports: $Exports<'electron-log/src/transports/ipc'>;
}
declare module 'electron-log/src/transports/remote.js' {
  declare module.exports: $Exports<'electron-log/src/transports/remote'>;
}
