// flow-typed signature: 75ff6f8cad27c9c3dfdc5f9d6aec9e46
// flow-typed version: <<STUB>>/electron-packager_v^14.1.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-packager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-packager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-packager/bin/electron-packager' {
  declare module.exports: any;
}

declare module 'electron-packager/src/cli' {
  declare module.exports: any;
}

declare module 'electron-packager/src/common' {
  declare module.exports: any;
}

declare module 'electron-packager/src/download' {
  declare module.exports: any;
}

declare module 'electron-packager/src/hooks' {
  declare module.exports: any;
}

declare module 'electron-packager/src/ignore' {
  declare module.exports: any;
}

declare module 'electron-packager/src' {
  declare module.exports: any;
}

declare module 'electron-packager/src/infer' {
  declare module.exports: any;
}

declare module 'electron-packager/src/linux' {
  declare module.exports: any;
}

declare module 'electron-packager/src/mac' {
  declare module.exports: any;
}

declare module 'electron-packager/src/platform' {
  declare module.exports: any;
}

declare module 'electron-packager/src/prune' {
  declare module.exports: any;
}

declare module 'electron-packager/src/targets' {
  declare module.exports: any;
}

declare module 'electron-packager/src/unzip' {
  declare module.exports: any;
}

declare module 'electron-packager/src/win32' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-packager/bin/electron-packager.js' {
  declare module.exports: $Exports<'electron-packager/bin/electron-packager'>;
}
declare module 'electron-packager/src/cli.js' {
  declare module.exports: $Exports<'electron-packager/src/cli'>;
}
declare module 'electron-packager/src/common.js' {
  declare module.exports: $Exports<'electron-packager/src/common'>;
}
declare module 'electron-packager/src/download.js' {
  declare module.exports: $Exports<'electron-packager/src/download'>;
}
declare module 'electron-packager/src/hooks.js' {
  declare module.exports: $Exports<'electron-packager/src/hooks'>;
}
declare module 'electron-packager/src/ignore.js' {
  declare module.exports: $Exports<'electron-packager/src/ignore'>;
}
declare module 'electron-packager/src/index' {
  declare module.exports: $Exports<'electron-packager/src'>;
}
declare module 'electron-packager/src/index.js' {
  declare module.exports: $Exports<'electron-packager/src'>;
}
declare module 'electron-packager/src/infer.js' {
  declare module.exports: $Exports<'electron-packager/src/infer'>;
}
declare module 'electron-packager/src/linux.js' {
  declare module.exports: $Exports<'electron-packager/src/linux'>;
}
declare module 'electron-packager/src/mac.js' {
  declare module.exports: $Exports<'electron-packager/src/mac'>;
}
declare module 'electron-packager/src/platform.js' {
  declare module.exports: $Exports<'electron-packager/src/platform'>;
}
declare module 'electron-packager/src/prune.js' {
  declare module.exports: $Exports<'electron-packager/src/prune'>;
}
declare module 'electron-packager/src/targets.js' {
  declare module.exports: $Exports<'electron-packager/src/targets'>;
}
declare module 'electron-packager/src/unzip.js' {
  declare module.exports: $Exports<'electron-packager/src/unzip'>;
}
declare module 'electron-packager/src/win32.js' {
  declare module.exports: $Exports<'electron-packager/src/win32'>;
}
