// flow-typed signature: 9d2b6b87f0227380f96ceaed2fbc3ae5
// flow-typed version: <<STUB>>/fix-path_v3.0.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fix-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fix-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fix-path/index' {
  declare module.exports: $Exports<'fix-path'>;
}
declare module 'fix-path/index.js' {
  declare module.exports: $Exports<'fix-path'>;
}
