// flow-typed signature: 3d77b62ee08fff74cc1f3af5f2474ba5
// flow-typed version: <<STUB>>/import-js_v^3.2.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'import-js/bin/importjs' {
  declare module.exports: any;
}

declare module 'import-js/bin/importjsd' {
  declare module.exports: any;
}

declare module 'import-js/build/__mocks__/FileUtils' {
  declare module.exports: any;
}

declare module 'import-js/build/__mocks__/fs' {
  declare module.exports: any;
}

declare module 'import-js/build/__mocks__/requireResolve' {
  declare module.exports: any;
}

declare module 'import-js/build/__mocks__/version' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/Configuration-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/ExportsStorage-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/FileUtils-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/findAllFiles-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/findCurrentImports-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/findExports-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/findJsModulesFor-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/findProjectRoot-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/findUndefinedIdentifiers-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/findUsedIdentifiers-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/Importer-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/ImportStatement-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/ImportStatements-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/initializeModuleFinder-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/JsModule-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/lastUpdate-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/ModuleFinder-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/normalizePath-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/parse-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/requireResolve-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/resolveImportPathAndMain-test' {
  declare module.exports: any;
}

declare module 'import-js/build/__tests__/Watcher-test' {
  declare module.exports: any;
}

declare module 'import-js/build/CommandLineEditor' {
  declare module.exports: any;
}

declare module 'import-js/build/Configuration' {
  declare module.exports: any;
}

declare module 'import-js/build/daemon' {
  declare module.exports: any;
}

declare module 'import-js/build/environments/meteorEnvironment' {
  declare module.exports: any;
}

declare module 'import-js/build/environments/nodeEnvironment' {
  declare module.exports: any;
}

declare module 'import-js/build/ExportsStorage' {
  declare module.exports: any;
}

declare module 'import-js/build/FileUtils' {
  declare module.exports: any;
}

declare module 'import-js/build/findAllFiles' {
  declare module.exports: any;
}

declare module 'import-js/build/findCurrentImports' {
  declare module.exports: any;
}

declare module 'import-js/build/findExports' {
  declare module.exports: any;
}

declare module 'import-js/build/findJsModulesFor' {
  declare module.exports: any;
}

declare module 'import-js/build/findPackageDependencies' {
  declare module.exports: any;
}

declare module 'import-js/build/findProjectRoot' {
  declare module.exports: any;
}

declare module 'import-js/build/findUndefinedIdentifiers' {
  declare module.exports: any;
}

declare module 'import-js/build/findUsedIdentifiers' {
  declare module.exports: any;
}

declare module 'import-js/build/forwardSlashes' {
  declare module.exports: any;
}

declare module 'import-js/build/Importer' {
  declare module.exports: any;
}

declare module 'import-js/build/importjs' {
  declare module.exports: any;
}

declare module 'import-js/build/ImportStatement' {
  declare module.exports: any;
}

declare module 'import-js/build/ImportStatements' {
  declare module.exports: any;
}

declare module 'import-js/build/initializeLogging' {
  declare module.exports: any;
}

declare module 'import-js/build/initializeModuleFinder' {
  declare module.exports: any;
}

declare module 'import-js/build/JsModule' {
  declare module.exports: any;
}

declare module 'import-js/build/lastUpdate' {
  declare module.exports: any;
}

declare module 'import-js/build/main' {
  declare module.exports: any;
}

declare module 'import-js/build/ModuleFinder' {
  declare module.exports: any;
}

declare module 'import-js/build/normalizePath' {
  declare module.exports: any;
}

declare module 'import-js/build/parse' {
  declare module.exports: any;
}

declare module 'import-js/build/readFile' {
  declare module.exports: any;
}

declare module 'import-js/build/requireResolve' {
  declare module.exports: any;
}

declare module 'import-js/build/rerouteConsoleLog' {
  declare module.exports: any;
}

declare module 'import-js/build/resolveImportPathAndMain' {
  declare module.exports: any;
}

declare module 'import-js/build/version' {
  declare module.exports: any;
}

declare module 'import-js/build/visitIdentifierNodes' {
  declare module.exports: any;
}

declare module 'import-js/build/Watcher' {
  declare module.exports: any;
}

declare module 'import-js/lib/__mocks__/FileUtils' {
  declare module.exports: any;
}

declare module 'import-js/lib/__mocks__/fs' {
  declare module.exports: any;
}

declare module 'import-js/lib/__mocks__/requireResolve' {
  declare module.exports: any;
}

declare module 'import-js/lib/__mocks__/version' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/Configuration-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/ExportsStorage-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/FileUtils-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/findAllFiles-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/findCurrentImports-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/findExports-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/findJsModulesFor-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/findProjectRoot-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/findUndefinedIdentifiers-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/findUsedIdentifiers-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/Importer-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/ImportStatement-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/ImportStatements-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/initializeModuleFinder-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/JsModule-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/lastUpdate-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/ModuleFinder-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/normalizePath-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/parse-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/requireResolve-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/resolveImportPathAndMain-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/__tests__/Watcher-test' {
  declare module.exports: any;
}

declare module 'import-js/lib/CommandLineEditor' {
  declare module.exports: any;
}

declare module 'import-js/lib/Configuration' {
  declare module.exports: any;
}

declare module 'import-js/lib/daemon' {
  declare module.exports: any;
}

declare module 'import-js/lib/environments/meteorEnvironment' {
  declare module.exports: any;
}

declare module 'import-js/lib/environments/nodeEnvironment' {
  declare module.exports: any;
}

declare module 'import-js/lib/ExportsStorage' {
  declare module.exports: any;
}

declare module 'import-js/lib/FileUtils' {
  declare module.exports: any;
}

declare module 'import-js/lib/findAllFiles' {
  declare module.exports: any;
}

declare module 'import-js/lib/findCurrentImports' {
  declare module.exports: any;
}

declare module 'import-js/lib/findExports' {
  declare module.exports: any;
}

declare module 'import-js/lib/findJsModulesFor' {
  declare module.exports: any;
}

declare module 'import-js/lib/findPackageDependencies' {
  declare module.exports: any;
}

declare module 'import-js/lib/findProjectRoot' {
  declare module.exports: any;
}

declare module 'import-js/lib/findUndefinedIdentifiers' {
  declare module.exports: any;
}

declare module 'import-js/lib/findUsedIdentifiers' {
  declare module.exports: any;
}

declare module 'import-js/lib/forwardSlashes' {
  declare module.exports: any;
}

declare module 'import-js/lib/Importer' {
  declare module.exports: any;
}

declare module 'import-js/lib/importjs' {
  declare module.exports: any;
}

declare module 'import-js/lib/ImportStatement' {
  declare module.exports: any;
}

declare module 'import-js/lib/ImportStatements' {
  declare module.exports: any;
}

declare module 'import-js/lib/initializeLogging' {
  declare module.exports: any;
}

declare module 'import-js/lib/initializeModuleFinder' {
  declare module.exports: any;
}

declare module 'import-js/lib/JsModule' {
  declare module.exports: any;
}

declare module 'import-js/lib/lastUpdate' {
  declare module.exports: any;
}

declare module 'import-js/lib/main' {
  declare module.exports: any;
}

declare module 'import-js/lib/ModuleFinder' {
  declare module.exports: any;
}

declare module 'import-js/lib/normalizePath' {
  declare module.exports: any;
}

declare module 'import-js/lib/parse' {
  declare module.exports: any;
}

declare module 'import-js/lib/readFile' {
  declare module.exports: any;
}

declare module 'import-js/lib/requireResolve' {
  declare module.exports: any;
}

declare module 'import-js/lib/rerouteConsoleLog' {
  declare module.exports: any;
}

declare module 'import-js/lib/resolveImportPathAndMain' {
  declare module.exports: any;
}

declare module 'import-js/lib/version' {
  declare module.exports: any;
}

declare module 'import-js/lib/visitIdentifierNodes' {
  declare module.exports: any;
}

declare module 'import-js/lib/Watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'import-js/bin/importjs.js' {
  declare module.exports: $Exports<'import-js/bin/importjs'>;
}
declare module 'import-js/bin/importjsd.js' {
  declare module.exports: $Exports<'import-js/bin/importjsd'>;
}
declare module 'import-js/build/__mocks__/FileUtils.js' {
  declare module.exports: $Exports<'import-js/build/__mocks__/FileUtils'>;
}
declare module 'import-js/build/__mocks__/fs.js' {
  declare module.exports: $Exports<'import-js/build/__mocks__/fs'>;
}
declare module 'import-js/build/__mocks__/requireResolve.js' {
  declare module.exports: $Exports<'import-js/build/__mocks__/requireResolve'>;
}
declare module 'import-js/build/__mocks__/version.js' {
  declare module.exports: $Exports<'import-js/build/__mocks__/version'>;
}
declare module 'import-js/build/__tests__/Configuration-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/Configuration-test'>;
}
declare module 'import-js/build/__tests__/ExportsStorage-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/ExportsStorage-test'>;
}
declare module 'import-js/build/__tests__/FileUtils-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/FileUtils-test'>;
}
declare module 'import-js/build/__tests__/findAllFiles-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/findAllFiles-test'>;
}
declare module 'import-js/build/__tests__/findCurrentImports-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/findCurrentImports-test'>;
}
declare module 'import-js/build/__tests__/findExports-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/findExports-test'>;
}
declare module 'import-js/build/__tests__/findJsModulesFor-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/findJsModulesFor-test'>;
}
declare module 'import-js/build/__tests__/findProjectRoot-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/findProjectRoot-test'>;
}
declare module 'import-js/build/__tests__/findUndefinedIdentifiers-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/findUndefinedIdentifiers-test'>;
}
declare module 'import-js/build/__tests__/findUsedIdentifiers-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/findUsedIdentifiers-test'>;
}
declare module 'import-js/build/__tests__/Importer-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/Importer-test'>;
}
declare module 'import-js/build/__tests__/ImportStatement-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/ImportStatement-test'>;
}
declare module 'import-js/build/__tests__/ImportStatements-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/ImportStatements-test'>;
}
declare module 'import-js/build/__tests__/initializeModuleFinder-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/initializeModuleFinder-test'>;
}
declare module 'import-js/build/__tests__/JsModule-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/JsModule-test'>;
}
declare module 'import-js/build/__tests__/lastUpdate-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/lastUpdate-test'>;
}
declare module 'import-js/build/__tests__/ModuleFinder-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/ModuleFinder-test'>;
}
declare module 'import-js/build/__tests__/normalizePath-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/normalizePath-test'>;
}
declare module 'import-js/build/__tests__/parse-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/parse-test'>;
}
declare module 'import-js/build/__tests__/requireResolve-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/requireResolve-test'>;
}
declare module 'import-js/build/__tests__/resolveImportPathAndMain-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/resolveImportPathAndMain-test'>;
}
declare module 'import-js/build/__tests__/Watcher-test.js' {
  declare module.exports: $Exports<'import-js/build/__tests__/Watcher-test'>;
}
declare module 'import-js/build/CommandLineEditor.js' {
  declare module.exports: $Exports<'import-js/build/CommandLineEditor'>;
}
declare module 'import-js/build/Configuration.js' {
  declare module.exports: $Exports<'import-js/build/Configuration'>;
}
declare module 'import-js/build/daemon.js' {
  declare module.exports: $Exports<'import-js/build/daemon'>;
}
declare module 'import-js/build/environments/meteorEnvironment.js' {
  declare module.exports: $Exports<'import-js/build/environments/meteorEnvironment'>;
}
declare module 'import-js/build/environments/nodeEnvironment.js' {
  declare module.exports: $Exports<'import-js/build/environments/nodeEnvironment'>;
}
declare module 'import-js/build/ExportsStorage.js' {
  declare module.exports: $Exports<'import-js/build/ExportsStorage'>;
}
declare module 'import-js/build/FileUtils.js' {
  declare module.exports: $Exports<'import-js/build/FileUtils'>;
}
declare module 'import-js/build/findAllFiles.js' {
  declare module.exports: $Exports<'import-js/build/findAllFiles'>;
}
declare module 'import-js/build/findCurrentImports.js' {
  declare module.exports: $Exports<'import-js/build/findCurrentImports'>;
}
declare module 'import-js/build/findExports.js' {
  declare module.exports: $Exports<'import-js/build/findExports'>;
}
declare module 'import-js/build/findJsModulesFor.js' {
  declare module.exports: $Exports<'import-js/build/findJsModulesFor'>;
}
declare module 'import-js/build/findPackageDependencies.js' {
  declare module.exports: $Exports<'import-js/build/findPackageDependencies'>;
}
declare module 'import-js/build/findProjectRoot.js' {
  declare module.exports: $Exports<'import-js/build/findProjectRoot'>;
}
declare module 'import-js/build/findUndefinedIdentifiers.js' {
  declare module.exports: $Exports<'import-js/build/findUndefinedIdentifiers'>;
}
declare module 'import-js/build/findUsedIdentifiers.js' {
  declare module.exports: $Exports<'import-js/build/findUsedIdentifiers'>;
}
declare module 'import-js/build/forwardSlashes.js' {
  declare module.exports: $Exports<'import-js/build/forwardSlashes'>;
}
declare module 'import-js/build/Importer.js' {
  declare module.exports: $Exports<'import-js/build/Importer'>;
}
declare module 'import-js/build/importjs.js' {
  declare module.exports: $Exports<'import-js/build/importjs'>;
}
declare module 'import-js/build/ImportStatement.js' {
  declare module.exports: $Exports<'import-js/build/ImportStatement'>;
}
declare module 'import-js/build/ImportStatements.js' {
  declare module.exports: $Exports<'import-js/build/ImportStatements'>;
}
declare module 'import-js/build/initializeLogging.js' {
  declare module.exports: $Exports<'import-js/build/initializeLogging'>;
}
declare module 'import-js/build/initializeModuleFinder.js' {
  declare module.exports: $Exports<'import-js/build/initializeModuleFinder'>;
}
declare module 'import-js/build/JsModule.js' {
  declare module.exports: $Exports<'import-js/build/JsModule'>;
}
declare module 'import-js/build/lastUpdate.js' {
  declare module.exports: $Exports<'import-js/build/lastUpdate'>;
}
declare module 'import-js/build/main.js' {
  declare module.exports: $Exports<'import-js/build/main'>;
}
declare module 'import-js/build/ModuleFinder.js' {
  declare module.exports: $Exports<'import-js/build/ModuleFinder'>;
}
declare module 'import-js/build/normalizePath.js' {
  declare module.exports: $Exports<'import-js/build/normalizePath'>;
}
declare module 'import-js/build/parse.js' {
  declare module.exports: $Exports<'import-js/build/parse'>;
}
declare module 'import-js/build/readFile.js' {
  declare module.exports: $Exports<'import-js/build/readFile'>;
}
declare module 'import-js/build/requireResolve.js' {
  declare module.exports: $Exports<'import-js/build/requireResolve'>;
}
declare module 'import-js/build/rerouteConsoleLog.js' {
  declare module.exports: $Exports<'import-js/build/rerouteConsoleLog'>;
}
declare module 'import-js/build/resolveImportPathAndMain.js' {
  declare module.exports: $Exports<'import-js/build/resolveImportPathAndMain'>;
}
declare module 'import-js/build/version.js' {
  declare module.exports: $Exports<'import-js/build/version'>;
}
declare module 'import-js/build/visitIdentifierNodes.js' {
  declare module.exports: $Exports<'import-js/build/visitIdentifierNodes'>;
}
declare module 'import-js/build/Watcher.js' {
  declare module.exports: $Exports<'import-js/build/Watcher'>;
}
declare module 'import-js/lib/__mocks__/FileUtils.js' {
  declare module.exports: $Exports<'import-js/lib/__mocks__/FileUtils'>;
}
declare module 'import-js/lib/__mocks__/fs.js' {
  declare module.exports: $Exports<'import-js/lib/__mocks__/fs'>;
}
declare module 'import-js/lib/__mocks__/requireResolve.js' {
  declare module.exports: $Exports<'import-js/lib/__mocks__/requireResolve'>;
}
declare module 'import-js/lib/__mocks__/version.js' {
  declare module.exports: $Exports<'import-js/lib/__mocks__/version'>;
}
declare module 'import-js/lib/__tests__/Configuration-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/Configuration-test'>;
}
declare module 'import-js/lib/__tests__/ExportsStorage-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/ExportsStorage-test'>;
}
declare module 'import-js/lib/__tests__/FileUtils-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/FileUtils-test'>;
}
declare module 'import-js/lib/__tests__/findAllFiles-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/findAllFiles-test'>;
}
declare module 'import-js/lib/__tests__/findCurrentImports-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/findCurrentImports-test'>;
}
declare module 'import-js/lib/__tests__/findExports-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/findExports-test'>;
}
declare module 'import-js/lib/__tests__/findJsModulesFor-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/findJsModulesFor-test'>;
}
declare module 'import-js/lib/__tests__/findProjectRoot-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/findProjectRoot-test'>;
}
declare module 'import-js/lib/__tests__/findUndefinedIdentifiers-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/findUndefinedIdentifiers-test'>;
}
declare module 'import-js/lib/__tests__/findUsedIdentifiers-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/findUsedIdentifiers-test'>;
}
declare module 'import-js/lib/__tests__/Importer-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/Importer-test'>;
}
declare module 'import-js/lib/__tests__/ImportStatement-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/ImportStatement-test'>;
}
declare module 'import-js/lib/__tests__/ImportStatements-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/ImportStatements-test'>;
}
declare module 'import-js/lib/__tests__/initializeModuleFinder-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/initializeModuleFinder-test'>;
}
declare module 'import-js/lib/__tests__/JsModule-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/JsModule-test'>;
}
declare module 'import-js/lib/__tests__/lastUpdate-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/lastUpdate-test'>;
}
declare module 'import-js/lib/__tests__/ModuleFinder-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/ModuleFinder-test'>;
}
declare module 'import-js/lib/__tests__/normalizePath-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/normalizePath-test'>;
}
declare module 'import-js/lib/__tests__/parse-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/parse-test'>;
}
declare module 'import-js/lib/__tests__/requireResolve-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/requireResolve-test'>;
}
declare module 'import-js/lib/__tests__/resolveImportPathAndMain-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/resolveImportPathAndMain-test'>;
}
declare module 'import-js/lib/__tests__/Watcher-test.js' {
  declare module.exports: $Exports<'import-js/lib/__tests__/Watcher-test'>;
}
declare module 'import-js/lib/CommandLineEditor.js' {
  declare module.exports: $Exports<'import-js/lib/CommandLineEditor'>;
}
declare module 'import-js/lib/Configuration.js' {
  declare module.exports: $Exports<'import-js/lib/Configuration'>;
}
declare module 'import-js/lib/daemon.js' {
  declare module.exports: $Exports<'import-js/lib/daemon'>;
}
declare module 'import-js/lib/environments/meteorEnvironment.js' {
  declare module.exports: $Exports<'import-js/lib/environments/meteorEnvironment'>;
}
declare module 'import-js/lib/environments/nodeEnvironment.js' {
  declare module.exports: $Exports<'import-js/lib/environments/nodeEnvironment'>;
}
declare module 'import-js/lib/ExportsStorage.js' {
  declare module.exports: $Exports<'import-js/lib/ExportsStorage'>;
}
declare module 'import-js/lib/FileUtils.js' {
  declare module.exports: $Exports<'import-js/lib/FileUtils'>;
}
declare module 'import-js/lib/findAllFiles.js' {
  declare module.exports: $Exports<'import-js/lib/findAllFiles'>;
}
declare module 'import-js/lib/findCurrentImports.js' {
  declare module.exports: $Exports<'import-js/lib/findCurrentImports'>;
}
declare module 'import-js/lib/findExports.js' {
  declare module.exports: $Exports<'import-js/lib/findExports'>;
}
declare module 'import-js/lib/findJsModulesFor.js' {
  declare module.exports: $Exports<'import-js/lib/findJsModulesFor'>;
}
declare module 'import-js/lib/findPackageDependencies.js' {
  declare module.exports: $Exports<'import-js/lib/findPackageDependencies'>;
}
declare module 'import-js/lib/findProjectRoot.js' {
  declare module.exports: $Exports<'import-js/lib/findProjectRoot'>;
}
declare module 'import-js/lib/findUndefinedIdentifiers.js' {
  declare module.exports: $Exports<'import-js/lib/findUndefinedIdentifiers'>;
}
declare module 'import-js/lib/findUsedIdentifiers.js' {
  declare module.exports: $Exports<'import-js/lib/findUsedIdentifiers'>;
}
declare module 'import-js/lib/forwardSlashes.js' {
  declare module.exports: $Exports<'import-js/lib/forwardSlashes'>;
}
declare module 'import-js/lib/Importer.js' {
  declare module.exports: $Exports<'import-js/lib/Importer'>;
}
declare module 'import-js/lib/importjs.js' {
  declare module.exports: $Exports<'import-js/lib/importjs'>;
}
declare module 'import-js/lib/ImportStatement.js' {
  declare module.exports: $Exports<'import-js/lib/ImportStatement'>;
}
declare module 'import-js/lib/ImportStatements.js' {
  declare module.exports: $Exports<'import-js/lib/ImportStatements'>;
}
declare module 'import-js/lib/initializeLogging.js' {
  declare module.exports: $Exports<'import-js/lib/initializeLogging'>;
}
declare module 'import-js/lib/initializeModuleFinder.js' {
  declare module.exports: $Exports<'import-js/lib/initializeModuleFinder'>;
}
declare module 'import-js/lib/JsModule.js' {
  declare module.exports: $Exports<'import-js/lib/JsModule'>;
}
declare module 'import-js/lib/lastUpdate.js' {
  declare module.exports: $Exports<'import-js/lib/lastUpdate'>;
}
declare module 'import-js/lib/main.js' {
  declare module.exports: $Exports<'import-js/lib/main'>;
}
declare module 'import-js/lib/ModuleFinder.js' {
  declare module.exports: $Exports<'import-js/lib/ModuleFinder'>;
}
declare module 'import-js/lib/normalizePath.js' {
  declare module.exports: $Exports<'import-js/lib/normalizePath'>;
}
declare module 'import-js/lib/parse.js' {
  declare module.exports: $Exports<'import-js/lib/parse'>;
}
declare module 'import-js/lib/readFile.js' {
  declare module.exports: $Exports<'import-js/lib/readFile'>;
}
declare module 'import-js/lib/requireResolve.js' {
  declare module.exports: $Exports<'import-js/lib/requireResolve'>;
}
declare module 'import-js/lib/rerouteConsoleLog.js' {
  declare module.exports: $Exports<'import-js/lib/rerouteConsoleLog'>;
}
declare module 'import-js/lib/resolveImportPathAndMain.js' {
  declare module.exports: $Exports<'import-js/lib/resolveImportPathAndMain'>;
}
declare module 'import-js/lib/version.js' {
  declare module.exports: $Exports<'import-js/lib/version'>;
}
declare module 'import-js/lib/visitIdentifierNodes.js' {
  declare module.exports: $Exports<'import-js/lib/visitIdentifierNodes'>;
}
declare module 'import-js/lib/Watcher.js' {
  declare module.exports: $Exports<'import-js/lib/Watcher'>;
}
