// flow-typed signature: 2f53fb40f2237502a50e1545523e1a43
// flow-typed version: <<STUB>>/livereload_v^0.8.2/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'livereload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'livereload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'livereload/bin/livereload' {
  declare module.exports: any;
}

declare module 'livereload/examples/server' {
  declare module.exports: any;
}

declare module 'livereload/ext/livereload' {
  declare module.exports: any;
}

declare module 'livereload/lib/command' {
  declare module.exports: any;
}

declare module 'livereload/lib/livereload' {
  declare module.exports: any;
}

// Filename aliases
declare module 'livereload/bin/livereload.js' {
  declare module.exports: $Exports<'livereload/bin/livereload'>;
}
declare module 'livereload/examples/server.js' {
  declare module.exports: $Exports<'livereload/examples/server'>;
}
declare module 'livereload/ext/livereload.js' {
  declare module.exports: $Exports<'livereload/ext/livereload'>;
}
declare module 'livereload/lib/command.js' {
  declare module.exports: $Exports<'livereload/lib/command'>;
}
declare module 'livereload/lib/livereload.js' {
  declare module.exports: $Exports<'livereload/lib/livereload'>;
}
