// flow-typed signature: b45c76b764d914980d349809e055c544
// flow-typed version: <<STUB>>/lookytalk_vgit+https://github.com/looky-cloud/lookytalk.git#v0.1.6/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lookytalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lookytalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lookytalk/bin/lookytalkc' {
  declare module.exports: any;
}

declare module 'lookytalk/compiler' {
  declare module.exports: any;
}

declare module 'lookytalk/parser/parser' {
  declare module.exports: any;
}

declare module 'lookytalk/reglob/reglob' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lookytalk/bin/lookytalkc.js' {
  declare module.exports: $Exports<'lookytalk/bin/lookytalkc'>;
}
declare module 'lookytalk/compiler.js' {
  declare module.exports: $Exports<'lookytalk/compiler'>;
}
declare module 'lookytalk/parser/parser.js' {
  declare module.exports: $Exports<'lookytalk/parser/parser'>;
}
declare module 'lookytalk/reglob/reglob.js' {
  declare module.exports: $Exports<'lookytalk/reglob/reglob'>;
}
