// flow-typed signature: 660b0790c523844026f386b02f1a6e42
// flow-typed version: <<STUB>>/moment-timezone_v^0.5.27/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-timezone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-timezone/builds/moment-timezone-with-data-10-year-range' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data-10-year-range.min' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data-1970-2030' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data-1970-2030.min' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data-2012-2022' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data-2012-2022.min' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone-with-data.min' {
  declare module.exports: any;
}

declare module 'moment-timezone/builds/moment-timezone.min' {
  declare module.exports: any;
}

declare module 'moment-timezone/moment-timezone-utils' {
  declare module.exports: any;
}

declare module 'moment-timezone/moment-timezone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-timezone/builds/moment-timezone-with-data-10-year-range.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data-10-year-range'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data-10-year-range.min.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data-10-year-range.min'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data-1970-2030.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data-1970-2030'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data-1970-2030.min.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data-1970-2030.min'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data-2012-2022.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data-2012-2022'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data-2012-2022.min.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data-2012-2022.min'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data'>;
}
declare module 'moment-timezone/builds/moment-timezone-with-data.min.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone-with-data.min'>;
}
declare module 'moment-timezone/builds/moment-timezone.min.js' {
  declare module.exports: $Exports<'moment-timezone/builds/moment-timezone.min'>;
}
declare module 'moment-timezone/index' {
  declare module.exports: $Exports<'moment-timezone'>;
}
declare module 'moment-timezone/index.js' {
  declare module.exports: $Exports<'moment-timezone'>;
}
declare module 'moment-timezone/moment-timezone-utils.js' {
  declare module.exports: $Exports<'moment-timezone/moment-timezone-utils'>;
}
declare module 'moment-timezone/moment-timezone.js' {
  declare module.exports: $Exports<'moment-timezone/moment-timezone'>;
}
