// flow-typed signature: 574b9ae774f6d7428193e91e1966c014
// flow-typed version: <<STUB>>/node-sass-chokidar_v^1.4.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass-chokidar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass-chokidar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-sass-chokidar/test/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-sass-chokidar/test/cli.js' {
  declare module.exports: $Exports<'node-sass-chokidar/test/cli'>;
}
