// flow-typed signature: f870b1e3d2b063ab683b9985ec0ed0fc
// flow-typed version: <<STUB>>/node-pipe_v0.1.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-pipe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-pipe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-pipe/main' {
  declare module.exports: any;
}

declare module 'node-pipe/test/pipe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-pipe/main.js' {
  declare module.exports: $Exports<'node-pipe/main'>;
}
declare module 'node-pipe/test/pipe.js' {
  declare module.exports: $Exports<'node-pipe/test/pipe'>;
}
