// flow-typed signature: ab09295df9e69be245c10312a57c9caf
// flow-typed version: <<STUB>>/on-idle_v3.1.4/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'on-idle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'on-idle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'on-idle/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'on-idle/example.js' {
  declare module.exports: $Exports<'on-idle/example'>;
}
declare module 'on-idle/index' {
  declare module.exports: $Exports<'on-idle'>;
}
declare module 'on-idle/index.js' {
  declare module.exports: $Exports<'on-idle'>;
}
