// flow-typed signature: feb9b679ea6ab8e1c02410bc74ef6221
// flow-typed version: <<STUB>>/opn_v^5.4.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'opn/index' {
  declare module.exports: $Exports<'opn'>;
}
declare module 'opn/index.js' {
  declare module.exports: $Exports<'opn'>;
}
