// flow-typed signature: d2bc67bb96cff110dc57534ece391206
// flow-typed version: <<STUB>>/opn_v^6.0.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'opn/index' {
  declare module.exports: $Exports<'open'>;
}
declare module 'opn/index.js' {
  declare module.exports: $Exports<'open'>;
}
