// flow-typed signature: 423fb060eeadeca5c001b2ad0bb17888
// flow-typed version: <<STUB>>/react-tooltip_v4.1.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tooltip/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tooltip/dist/index.es.js' {
  declare module.exports: $Exports<'react-tooltip/dist/index.es'>;
}
declare module 'react-tooltip/dist/index' {
  declare module.exports: $Exports<'react-tooltip/dist'>;
}
declare module 'react-tooltip/dist/index.js' {
  declare module.exports: $Exports<'react-tooltip/dist'>;
}
