// flow-typed signature: e4f54cc3703b01636427d2c4feab4d3e
// flow-typed version: <<STUB>>/react-measure_v^2.2.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-measure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-measure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-measure/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-measure/dist/index.esm' {
  declare module.exports: any;
}

declare module 'react-measure/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-measure/src/get-content-rect' {
  declare module.exports: any;
}

declare module 'react-measure/src/get-types' {
  declare module.exports: any;
}

declare module 'react-measure/src/index' {
  declare module.exports: any;
}

declare module 'react-measure/src/Measure' {
  declare module.exports: any;
}

declare module 'react-measure/src/with-content-rect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-measure/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-measure/dist/index.cjs'>;
}
declare module 'react-measure/dist/index.esm.js' {
  declare module.exports: $Exports<'react-measure/dist/index.esm'>;
}
declare module 'react-measure/dist/index.umd.js' {
  declare module.exports: $Exports<'react-measure/dist/index.umd'>;
}
declare module 'react-measure/src/get-content-rect.js' {
  declare module.exports: $Exports<'react-measure/src/get-content-rect'>;
}
declare module 'react-measure/src/get-types.js' {
  declare module.exports: $Exports<'react-measure/src/get-types'>;
}
declare module 'react-measure/src/index.js' {
  declare module.exports: $Exports<'react-measure/src/index'>;
}
declare module 'react-measure/src/Measure.js' {
  declare module.exports: $Exports<'react-measure/src/Measure'>;
}
declare module 'react-measure/src/with-content-rect.js' {
  declare module.exports: $Exports<'react-measure/src/with-content-rect'>;
}
