// flow-typed signature: c23ccb8c353261cc6f9581d293fa1861
// flow-typed version: <<STUB>>/react-day-picker_v^7.4.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-day-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-day-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-day-picker/DayPicker' {
  declare module.exports: any;
}

declare module 'react-day-picker/DayPickerInput' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/daypicker' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/daypicker.min' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/addons' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/addons/LocaleUtils' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/addons/MomentLocaleUtils' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/Caption' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/classNames' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/DateUtils' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/Day' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/DayPicker' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/DayPickerInput' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/Helpers' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/keys' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/LocaleUtils' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/ModifiersUtils' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/Month' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/Navbar' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/PropTypes' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/Weekday' {
  declare module.exports: any;
}

declare module 'react-day-picker/lib/src/Weekdays' {
  declare module.exports: any;
}

declare module 'react-day-picker/moment' {
  declare module.exports: any;
}

declare module 'react-day-picker/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-day-picker/DayPicker.js' {
  declare module.exports: $Exports<'react-day-picker/DayPicker'>;
}
declare module 'react-day-picker/DayPickerInput.js' {
  declare module.exports: $Exports<'react-day-picker/DayPickerInput'>;
}
declare module 'react-day-picker/lib/daypicker.js' {
  declare module.exports: $Exports<'react-day-picker/lib/daypicker'>;
}
declare module 'react-day-picker/lib/daypicker.min.js' {
  declare module.exports: $Exports<'react-day-picker/lib/daypicker.min'>;
}
declare module 'react-day-picker/lib/src/addons/index' {
  declare module.exports: $Exports<'react-day-picker/lib/src/addons'>;
}
declare module 'react-day-picker/lib/src/addons/index.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/addons'>;
}
declare module 'react-day-picker/lib/src/addons/LocaleUtils.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/addons/LocaleUtils'>;
}
declare module 'react-day-picker/lib/src/addons/MomentLocaleUtils.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/addons/MomentLocaleUtils'>;
}
declare module 'react-day-picker/lib/src/Caption.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/Caption'>;
}
declare module 'react-day-picker/lib/src/classNames.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/classNames'>;
}
declare module 'react-day-picker/lib/src/DateUtils.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/DateUtils'>;
}
declare module 'react-day-picker/lib/src/Day.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/Day'>;
}
declare module 'react-day-picker/lib/src/DayPicker.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/DayPicker'>;
}
declare module 'react-day-picker/lib/src/DayPickerInput.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/DayPickerInput'>;
}
declare module 'react-day-picker/lib/src/Helpers.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/Helpers'>;
}
declare module 'react-day-picker/lib/src/index' {
  declare module.exports: $Exports<'react-day-picker/lib/src'>;
}
declare module 'react-day-picker/lib/src/index.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src'>;
}
declare module 'react-day-picker/lib/src/keys.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/keys'>;
}
declare module 'react-day-picker/lib/src/LocaleUtils.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/LocaleUtils'>;
}
declare module 'react-day-picker/lib/src/ModifiersUtils.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/ModifiersUtils'>;
}
declare module 'react-day-picker/lib/src/Month.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/Month'>;
}
declare module 'react-day-picker/lib/src/Navbar.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/Navbar'>;
}
declare module 'react-day-picker/lib/src/PropTypes.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/PropTypes'>;
}
declare module 'react-day-picker/lib/src/Weekday.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/Weekday'>;
}
declare module 'react-day-picker/lib/src/Weekdays.js' {
  declare module.exports: $Exports<'react-day-picker/lib/src/Weekdays'>;
}
declare module 'react-day-picker/moment.js' {
  declare module.exports: $Exports<'react-day-picker/moment'>;
}
declare module 'react-day-picker/utils.js' {
  declare module.exports: $Exports<'react-day-picker/utils'>;
}
