// flow-typed signature: 72685d13622cb22bb4bccbed8dcd1ca7
// flow-typed version: <<STUB>>/set-tz_v0.2.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'set-tz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'set-tz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'set-tz/tests/set-tz-iana.spec' {
  declare module.exports: any;
}

declare module 'set-tz/tests/set-tz-windows.spec' {
  declare module.exports: any;
}

declare module 'set-tz/tests/set-tz.spec' {
  declare module.exports: any;
}

declare module 'set-tz/utc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'set-tz/index' {
  declare module.exports: $Exports<'set-tz'>;
}
declare module 'set-tz/index.js' {
  declare module.exports: $Exports<'set-tz'>;
}
declare module 'set-tz/tests/set-tz-iana.spec.js' {
  declare module.exports: $Exports<'set-tz/tests/set-tz-iana.spec'>;
}
declare module 'set-tz/tests/set-tz-windows.spec.js' {
  declare module.exports: $Exports<'set-tz/tests/set-tz-windows.spec'>;
}
declare module 'set-tz/tests/set-tz.spec.js' {
  declare module.exports: $Exports<'set-tz/tests/set-tz.spec'>;
}
declare module 'set-tz/utc.js' {
  declare module.exports: $Exports<'set-tz/utc'>;
}
