// flow-typed signature: 1a958a1df415c8d7573bfcd7a0c44ebb
// flow-typed version: <<STUB>>/spectron-fake-dialog_v0.0.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spectron-fake-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spectron-fake-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spectron-fake-dialog/preload' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spectron-fake-dialog/index' {
  declare module.exports: $Exports<'spectron-fake-dialog'>;
}
declare module 'spectron-fake-dialog/index.js' {
  declare module.exports: $Exports<'spectron-fake-dialog'>;
}
declare module 'spectron-fake-dialog/preload.js' {
  declare module.exports: $Exports<'spectron-fake-dialog/preload'>;
}
