// flow-typed signature: fb0a8d047d024a5894af0bca0a74c6e6
// flow-typed version: <<STUB>>/text-encoding_v^0.6.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-encoding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-encoding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'text-encoding/lib/encoding-indexes' {
  declare module.exports: any;
}

declare module 'text-encoding/lib/encoding' {
  declare module.exports: any;
}

// Filename aliases
declare module 'text-encoding/index' {
  declare module.exports: $Exports<'text-encoding'>;
}
declare module 'text-encoding/index.js' {
  declare module.exports: $Exports<'text-encoding'>;
}
declare module 'text-encoding/lib/encoding-indexes.js' {
  declare module.exports: $Exports<'text-encoding/lib/encoding-indexes'>;
}
declare module 'text-encoding/lib/encoding.js' {
  declare module.exports: $Exports<'text-encoding/lib/encoding'>;
}
