// flow-typed signature: d8c1a51144731003f5b387d3780a82fa
// flow-typed version: <<STUB>>/whatwg-fetch_v3.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'whatwg-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'whatwg-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'whatwg-fetch/dist/fetch.umd' {
  declare module.exports: any;
}

declare module 'whatwg-fetch/fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'whatwg-fetch/dist/fetch.umd.js' {
  declare module.exports: $Exports<'whatwg-fetch/dist/fetch.umd'>;
}
declare module 'whatwg-fetch/fetch.js' {
  declare module.exports: $Exports<'whatwg-fetch/fetch'>;
}
