// flow-typed signature: cfe894af26dee76da1c9ed58aff53163
// flow-typed version: <<STUB>>/zealot_v0.0.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zealot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zealot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zealot/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zealot/bundle.js' {
  declare module.exports: $Exports<'zealot/bundle'>;
}
