// flow-typed signature: c9c58a3dd08baa571d948aa24f312370
// flow-typed version: <<STUB>>/zq_v/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zq' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zq/reglob/reglob' {
  declare module.exports: any;
}

declare module 'zq/zql/main/main' {
  declare module.exports: any;
}

declare module 'zq/zql/zql' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zq/reglob/reglob.js' {
  declare module.exports: $Exports<'zq/reglob/reglob'>;
}
declare module 'zq/zql/main/main.js' {
  declare module.exports: $Exports<'zq/zql/main/main'>;
}
declare module 'zq/zql/zql.js' {
  declare module.exports: $Exports<'zq/zql/zql'>;
}
