// flow-typed signature: 6b6a2d59e6697657d23961d320482d3f
// flow-typed version: <<STUB>>/@babel/plugin-proposal-object-rest-spread_v^7.2.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-object-rest-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-object-rest-spread' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-object-rest-spread/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-object-rest-spread/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-object-rest-spread/lib/index'>;
}
