import Log from "../models/Log"

export default () =>
  new Log(
    [
      "0",
      "conn",
      "1425612054.369843",
      "Cynwae4qh1GxM82hQ2",
      "192.168.0.50",
      "1900",
      "239.255.255.250",
      "1900",
      "udp",
      "-",
      "2.000293",
      "282",
      "0",
      "S0",
      "-",
      "-",
      "0",
      "D",
      "3",
      "366",
      "0",
      "0",
      "(empty)"
    ],
    [
      {name: "_td", type: "int"},
      {name: "_path", type: "string"},
      {name: "ts", type: "time"},
      {name: "uid", type: "string"},
      {name: "id.orig_h", type: "addr"},
      {name: "id.orig_p", type: "port"},
      {name: "id.resp_h", type: "addr"},
      {name: "id.resp_p", type: "port"},
      {name: "proto", type: "enum"},
      {name: "service", type: "string"},
      {name: "duration", type: "interval"},
      {name: "orig_bytes", type: "count"},
      {name: "resp_bytes", type: "count"},
      {name: "conn_state", type: "string"},
      {name: "local_orig", type: "bool"},
      {name: "local_resp", type: "bool"},
      {name: "missed_bytes", type: "count"},
      {name: "history", type: "string"},
      {name: "orig_pkts", type: "count"},
      {name: "orig_ip_bytes", type: "count"},
      {name: "resp_pkts", type: "count"},
      {name: "resp_ip_bytes", type: "count"},
      {name: "tunnel_parents", type: "set[string]"}
    ]
  )
