export const MD5_CORRELATION = "zui-zeek/md5-correlation"
export const TX_HOSTS_CORRELATION = "zui-zeek/tx-hosts-correlation"
export const RX_HOSTS_CORRELATION = "zui-zeek/rx-hosts-correlation"
export const FILENAME_CORRELATION = "zui-zeek/filename-correlation"
export const UID_CORRELATION = "zui-zeek/uid-correlation"
