import "regenerator-runtime/runtime"
import "@testing-library/jest-dom"
import "./mock-network"
import "./polyfill-dom"
import "./polyfill-fetch"
import "./setup-dom"
import "./setup-ipc"
import "./setup-enzyme"
