import createLocator from "./createLocator"

export const defaultModalButton = createLocator("default_modal_button")
export const viewerResults = createLocator("viewer_results")
export const ingestProgressBar = createLocator("ingest_progress_bar")
export const toolbarExportButton = createLocator("toolbar_export_button")
export const popNoticeLocator = createLocator("pop_notice")
export const toastLocator = createLocator("toast_notice")
export const hookLogLocator = createLocator("hook_log")
export const submitButton = createLocator("submit_button")
export const htmlContextMenu = createLocator("contextMenu")
export const currentPoolItem = createLocator("current_pool_item")
export const poolItem = createLocator("pool_item")
export const detailPane = createLocator("detail_pane")
export const brimQueryLib = createLocator("brim_query_lib_group")
