name: Advance Super

on:
  workflow_dispatch:

jobs:
  advance-super:
    name: Advance Super
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
        with:
          # ref defaults to github.sha, which is fixed at the time a run
          # is triggered. Using github.ref ensures a run that waits for
          # the concurrency group will see any commits pushed by the runs
          # that caused it to wait, reducing push failures down below.
          ref: ${{ github.ref }}
          # We need a token with permission to push.
          token: ${{ secrets.PAT_TOKEN }}
      - uses: ./.github/actions/setup-app
